### ISSUE TITLE
Laravel sail with Meilisearch: write a Wiki page

### ISSUE THREAD

**Issue by marky291** [shokme/laravel-scout-meilisearch#67]
Not sure if right place to put this, but since laravel valet is going to be removed in the future.

 I was wondering if this laravel driver supports the usage of laravel sail (dockerized container) https://laravel.com/docs/8.x/sail. 

Or if there could be documentation to show how to implement, I have been unable to get this working. 

The instance it creates does not get read by **this driver** is the impression I am getting, though I could easily be wrong.

<img width="1299" alt="Screenshot 2020-12-18 at 00 46 38" src="https://user-images.githubusercontent.com/5384515/102560635-9c03d380-40ca-11eb-9798-65dea4e75ce6.png">

<img width="1379" alt="Screenshot 2020-12-18 at 00 47 06" src="https://user-images.githubusercontent.com/5384515/102560641-9f975a80-40ca-11eb-9c68-c4e7afb10d12.png">

<img width="331" alt="Screenshot 2020-12-18 at 00 50 12" src="https://user-images.githubusercontent.com/5384515/102560800-04eb4b80-40cb-11eb-9a9c-b7c187e1349c.png">

**Comment by shokme** [comment]
Hello @marky291 
Is hard to write how works docker.
But 0.0.0.0:7700 just mean meilisearch bind the port 7700 on your localhost to be available on your machine. (localhost:7700)
here you are in a laravel container, so you don't want to communicate by `port` but by `service`.

If you take a closer look at your `.env` you can see
`DB_HOST=mysql`
`MAIL_HOST=mailhog`
They refer to the service name in your `docker-compose.yml`
so for meilisearch you need to do
`MEILISEARCH_HOST=meilisearch:7700`
:7700 because there is no MEILISEARCH_PORT env

I don't know if it's clear for you, this is hard to me to explain how works docker.

docker-compose.yml you need to add this
```yml
    meilisearch:
      image: 'getmeili/meilisearch:latest'
      ports:
          - 7700:7700
      networks:
          - sail
      volumes:
      - 'meilisearch:/data.ms'

volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    meilisearch:
        driver: local
```
